# Generated by Django 2.1.4 on 2019-01-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=20)),
                ('sell', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('city',),
            },
        ),
    ]
