# Generated by Django 2.1.4 on 2019-01-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='url',
            new_name='link',
        ),
    ]
