# Generated by Django 2.1.4 on 2019-01-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190102_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AlterField(
            model_name='entry',
            name='address',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='distance',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lat',
            field=models.CharField(default='0.0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lng',
            field=models.CharField(default='0.0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sell',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.CharField(default='0:00', max_length=20, null=True),
        ),
    ]
